[Step2] 강경, James
yagom-academy/ios-project-manager-server pull request #41
Opened 2021-07-29 08:39 UTC by KangKyung

@wonhee009 
라자냐!!  step2를 완료했어요🚌
이번에도 빈틈없는, 멋진 리뷰 부탁드리겠습니다👍🏻

# 배포 성공 URL

- [Test URL-1](https://ios-project-manager.herokuapp.com)
<img width="879" alt="스크린샷 2021-07-29 오후 5 03 11" src="https://user-images.githubusercontent.com/38858863/127455230-eec0bbcb-c64e-44fa-bd6a-6cf5a75c2451.png">

- [Test URL-2](https://ios-project-manager.herokuapp.com/hello)
<img width="913" alt="스크린샷 2021-07-29 오후 5 03 38" src="https://user-images.githubusercontent.com/38858863/127455252-3a9b09fb-a3ee-43a2-95ef-5cc120cbc1c5.png">

# Fluent 프레임워크를 사용한 모델과 마이그레이션

```swift
public func configure(_ app: Application) throws {
    if let databaseURL = Environment.get("DATABASE_URL"), var postgresConfig = PostgresConfiguration(url: databaseURL) {
        postgresConfig.tlsConfiguration = .makeClientConfiguration()
        app.databases.use(.postgres(
            configuration: postgresConfig
        ), as: .psql)
    } else {
        // ...
    }
    try routes(app)
    
    app.migrations.add(TaskMigration())
}
```

```swift
import Fluent
import FluentPostgresDriver

struct TaskMigration: Migration {
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        let category = database.enum("category")
            .case("toDo")
            .case("doing")
            .case("done")
            .create()
        
        return database.enum("category").read().flatMap { category in
            database.schema(Task.schema)
                .id()
                .field("title", .string, .required)
                .field("content", .string, .required)
                .field("deadline_date", .date, .required)
                .create()
        }
    }
    
    func revert(on database: Database) -> EventLoopFuture<Void> {
        return database.schema(Task.schema).delete()
    }   
}
```
___

눈에 거슬리는(?)부분은 이번에도 가차없이 지적✅ 해주세요🙏🏼

2021-07-29 13:02 UTC, wonhee009 requested changes
@KangKyung @inwoodev 강경, James 스텝2 PR 수고하셨습니다🎉
전체적으로 메서드들이 깔끔하다고 느꼈습니다!
남겨둔 리뷰 확인 부탁드립니다🙏

2021-07-29 13:02 UTC, wonhee009 commented on ProjectManagerServer/Sources/App/Models/Task.swift
> +    var deadline_date: Date
스네이크 케이스를 사용하신 이유가 있을까요?

2021-07-29 13:02 UTC, wonhee009 commented on ProjectManagerServer/Sources/App/Migrations/TaskMigration.swift
> +            .case("toDo")
API 문서에는 `todo`인거 같은데 혼란을 줄 여지가 있는 부분 같아요🤔

2021-07-29 13:02 UTC, wonhee009 commented on ProjectManagerServer/Sources/App/configure.swift
> +    }
현재 `else`에서 아무런 작동을 하지 않는거 같은데 남겨두신 이유가 있을까요?

2021-07-29 13:13 UTC, KangKyung commented on ProjectManagerServer/Sources/App/configure.swift
> +    }
좀 더 주의깊게 보고 PR을 보냈어야 했는데..😢
삭제했습니다! 꼼꼼한 리뷰 감사합니다🙏🏼

2021-07-29 13:15 UTC, KangKyung commented on ProjectManagerServer/Sources/App/Migrations/TaskMigration.swift
> +            .case("toDo")
네.. `todo`가 맞는 형태인데, 코드 작성중에 실수하였습니다😭
고치도록 하겠습니다‼️

2021-07-29 14:40 UTC, KangKyung commented on ProjectManagerServer/Sources/App/Models/Task.swift
> +    var deadline_date: Date
카멜케이스도 고려했는데요, 저희가 프로젝트 진행하면서 받은 json의 key는 모두 다 스네이크 케이스로 구현되어있었어요.
이를 통해 서버 쪽에서 json 데이터를 생성할 때 대부분 스네이크 케이스로 작성된다고 생각했고 실무에서도 그럴거라고 생각했습니다.
그렇기 때문에 최대한 실무와 비슷한 환경을 만들려고 스네이크 케이스로 작성해보았습니다.
라자냐는 어떻게 생각하시나요? 카멜케이스로 수정하는 것이 나을까요?

2021-07-29 14:45 UTC, KangKyung commented
@wonhee009 
라자냐! 저희가 Step2 PR을 보내고 Step3를 이미 어느정도 진행해 버려서..
변경하겠다고 코멘트한 부분은 Stpe3 PR에서 보여드리도록 하겠습니다😭
스네이크 케이스에 대해 코멘트를 남긴 부분 피드백 부탁드리고요
괜찮으시다면, merge부탁드리겠습니다🙏🏼

2021-07-30 02:03 UTC, wonhee009 commented on ProjectManagerServer/Sources/App/Models/Task.swift
> +    var deadline_date: Date
음…. 저도 실무에서는 스네이크 케이스를 많이 봤었어요!
근데 그 부분은 실무에서 대부분 사용하는 언어/프레임워크가 스네이크 케이스를 쓰는 경우였거든요!
스위프트로 구성된 서버인만큼 카멜 케이스로 구성이 좀 더 낫지 않나라는 생각을 했거든요.
이 부분은 그냥 제 의견이니 강경과 James가 이유가 있다면 괜찮습니다!

2021-07-30 02:04 UTC, wonhee009 commented
@KangKyung @inwoodev 넵! 스텝2 수고하셨습니다!🙌

2021-07-30 02:04 UTC, merged