[Step3] 강경, James
yagom-academy/ios-project-manager-server pull request #45
Opened 2021-07-30 13:35 UTC by KangKyung

@wonhee009 
라자냐!!  step3 PR입니다📝
이번에도 꼭꼭 숨어있는 🪲가 있는지, 날카로운🦅 리뷰 부탁드려요!

# Step2에서 변경한 부분

### GET에서 category(todo, doing, done)별 호출방식 변경

- 변경 전

```swift
task.group(":category") { task in
    task.get(use: readCategorizedTasks)
}
```

- 변경 후 (파라미터로 가져오던 방식을 path로 수정)

```swift
task.get("todo", use: readTodoTasks)
task.get("doing", use: readDoingTasks)
task.get("done", use: readDoneTasks)
```

### POST와 DELTE진행시 id값에대한 처리

- 변경 전

<img width="691" alt="스크린샷 2021-07-30 오후 9 54 54" src="https://user-images.githubusercontent.com/38858863/127657051-a0aa9a79-a59e-476b-80c0-adcb66aaaf31.png">

- 변경 후 (body의 id값 삭제)

<img width="692" alt="스크린샷 2021-07-30 오후 10 06 53" src="https://user-images.githubusercontent.com/38858863/127657292-3bbe6ba7-b3f8-4c9a-8b17-65a9213ccd52.png">

# 구현한 검증

### Request header의 Content-Type 유효성 검사

<img width="686" alt="Request header의 Content-Type 유효성 검사" src="https://user-images.githubusercontent.com/38858863/127657075-0a1b882d-0ae3-44da-b7de-ad785455da6d.png">

### Request body 유효성 검사

<img width="619" alt="Request body 유효성 검사" src="https://user-images.githubusercontent.com/38858863/127657096-3629cb12-4592-4c74-aaf1-16364d643679.png">

# 고민한 부분🤔

### GET방식에 관한 고민

```swift
func boot(routes: RoutesBuilder) throws {
        let task = routes.grouped("project")
        
        task.group(":category") { task in
            task.get(use: readTodoTasks)
            task.get(use: readDoingTasks)
            task.get(use: readDoneTasks)
        }

        // ...        

    }
}
```

특정 taskList를 파라미터방식으로 접근해서 get하기 위해 위와 같은 코드를 작성했었는데요. 저렇게 작성하니 url 끝에 /todo 가 들어와도 위 코드 블럭에있는 마지막 get 메서드가 호출되면서 category가 todo가 아닌 done인 task 만 불러와지는 문제를 겪었습니다.

이를 해결하고자 return Task.find파라미터를 통해서 접근해 보려고도 했는데 사진에 나와있는 것처럼 특정 task를 담은 배열이 아닌 task타입으로만 반환이 되더라구요.

![image](https://user-images.githubusercontent.com/38858863/127659181-c83087e2-bd27-4f0a-a116-6ec8a4360b55.png)

그래서 고심끝에 내린 결론은 저희가 path를 구체적으로 정의를 해서 그쪽으로 get request를 보내도록 했습니다. 라자냐가 보시기에 이런 방식이 어색한지 궁금하고 어색하다면 어떤식으로 개선이 가능한지 궁금합니다.

### optional type에 대한 고민

<img width="607" alt="스크린샷 2021-07-30 오후 10 34 21" src="https://user-images.githubusercontent.com/38858863/127660739-1d592bd6-b558-40d9-9078-498788856f4e.png">

클라이언트 측과 이야기를 나누어봤는데요, 아무래도 사용자가 상세내용을 빈 값으로 둔채 할 일을 작성할 수도 있어야한다고 결론을 내렸어요.
그래서 content를 옵셔널String 타입으로 지정 해 주었어요.
그런데 이렇게 하면 client쪽에서 post를 할 때, 모델의 content의 key 값이 틀린경우에 null값으로 post가 되는 문제를 확인했어요.
이 문제를 해결할 방법이 떠오르질 않아서..😭
라자냐에게 조언을 받고 싶어요🙏🏼
만약, 해결할 수 없다면 이 문제를 클라이언트에게 따로 알려줘야 할까요?
그렇다면 어떤 식으로 알려주는 것이 좋을까요??
(API문서에 남기는 것이 좋을까요?🧐)

___

조금이라도 인상이 찌푸려지는(?)부분에 대한 지적✅은 언제나 환영입니다🎉

2021-08-02 08:27 UTC, wonhee009 requested changes
@KangKyung @inwoodev 강경, James 스텝3 수고하셨습니다.🎉

> GET방식에 관한 고민

현재 방식에서 어색한 점은 없는거 같아요.
```swift
task.get("todo", use: readTodoTasks)
task.get("doing", use: readDoingTasks)
task.get("done", use: readDoneTasks)
```
위의 코드에서 쓰이는 `readTodoTasks`, `readDoingTasks`, `readDoneTasks`의 로직이 동일하다고 보여지는데요.
이부분을 메서드 하나로 뭉칠 수 있지 않을까라는 생각이 드네요.🤔

> optional type에 대한 고민

**모델의 content의 key 값이 틀린경우**라는게 어떤 경우인가요?
모델에 "content2"와 같은 키값을 사용한 경우인가요?

2021-08-02 08:27 UTC, wonhee009 commented on ProjectManagerServer/Sources/App/Models/TaskError.swift
> +
`error`를 enum으로 설정한 부분 좋습니다!🎉
하지만 `contentTypeIsNotJson` 이외의 error가 발생할 일은 없을까요?

2021-08-02 08:27 UTC, wonhee009 commented on ProjectManagerServer/Sources/App/Strings/Strings.swift
> +}
파일 이름과 enum 이름 모두 `Strings`네요.
좀 더 명확한 네이밍으로 개선해보는건 어때요?🤔

2021-08-02 08:27 UTC, wonhee009 commented on ProjectManagerServer/Sources/App/Controllers/TaksController.swift
> +            }
`return` 안에 `return`인데 이 부분 개선할 수 있을까요?🤔

2021-08-02 08:27 UTC, wonhee009 commented on ProjectManagerServer/Sources/App/Controllers/TaksController.swift
> +            .transform(to: .ok)
`return`에서 많은 일을 해주고 있는거 같아요!
이런 부분은 가독성이 떨어진다고 생각되는데 어떻게 생각하시나요?🤔

2021-08-03 06:08 UTC, KangKyung commented on ProjectManagerServer/Sources/App/Models/TaskError.swift
> +
이외에는, 모델의 content의 key 값이 틀린경우 error가 발생할 수 있을거 같아요!
해당 부분은 `optional type에 대한 고민`에 대한 라자냐의 피드백을 듣고나서 고치도록 하겠습니다‼️

2021-08-03 06:19 UTC, KangKyung commented on ProjectManagerServer/Sources/App/Strings/Strings.swift
> +}
좀 더 가독성있는 이름으로 변경하였습니다!
`Strings.ContentType` -> `ContentType.string`
`Strings.JsonType` -> `ContentType.jsonType`

2021-08-03 06:20 UTC, KangKyung commented on ProjectManagerServer/Sources/App/Controllers/TaksController.swift
> +            }
안에있는 `return`부분을 상수로 빼내었습니다!

2021-08-03 06:21 UTC, KangKyung commented on ProjectManagerServer/Sources/App/Controllers/TaksController.swift
> +            .transform(to: .ok)
여러개의 가독성있는 이름의 변수로 역할을 나누어서 해당 부분을 개선하였습니다!

2021-08-03 06:49 UTC, KangKyung commented
@wonhee009 
피드백 주신대로, 코드를 개선하였습니다‼️

> task.get("todo", use: readTodoTasks)
task.get("doing", use: readDoingTasks)
task.get("done", use: readDoneTasks)
위의 코드에서 쓰이는 readTodoTasks, readDoingTasks, readDoneTasks의 로직이 동일하다고 보여지는데요.
이부분을 메서드 하나로 뭉칠 수 있지 않을까라는 생각이 드네요.🤔

곰곰히 생각해 보았던 부분입니다..!
저희역시 유사한 코드는 재사용하는 것이 맞다고 생각해요!
그래서 어떻게든 합쳐보려고 했는데... 생각대로 잘 되지 않았어요😢
```swift
task.get(["todo", "doing", "done"], use: readTasks)
```
이런 식으로, `"todo"`, `"doing"`, `"done"`가 들어올 때 `readTasks`함수가 호출되도록 만들고
`readTasks`함수에서 각 경우에 대한 분기처리를 진행하려고 했는데
```swift
func readTasks(request: Request) throws -> EventLoopFuture<[Task]> {
        switch request.parameters.get("") { // <- 이 부분이 문제입니다...
        case "todo":
            return Task.query(on: request.db).filter(\.$category == .todo).all()
        case "doing":
            return Task.query(on: request.db).filter(\.$category == .doing).all()
        case "done":
            return Task.query(on: request.db).filter(\.$category == .done).all()
        default:
            return Task.query(on: request.db).filter(\.$category == .todo).all()
        }
    }
```
위의 ~이상한~코드와 같이, 함수 안에서는 `"todo"`인지, `"doing"`인지, `"done"`인지를 알 수 있는 방법이 없더라고요..
(저희가 방법을 못찾은 걸까요?😭)

더불어, 코드가 중복 되더라도 하나의 책임을 갖는 메서드를 여러개 만드는 것이
하나의 메서드 안에서 분기처리를 하는 것 보다 더 객체지향적(단일책임원칙)이라고 생각이 문득 들었는데요..!
라자냐는 이 부분에 대해서는 어떻게 생각하실지 궁금해요🤔

> 모델의 content의 key 값이 틀린경우라는게 어떤 경우인가요?
모델에 "content2"와 같은 키값을 사용한 경우인가요?

저희는 request시 `content`라는 키 값이 없는경우, 사용자가 아무내용도 입력하지 않은 것이라고 판단하여
데이터베이스의 `content`칼럼에 `null`이 들어가도록 설계했어요!

하지만,
<img width="607" alt="스크린샷 2021-07-30 오후 10 34 21" src="https://user-images.githubusercontent.com/38858863/127660739-1d592bd6-b558-40d9-9078-498788856f4e.png">

위 사진은 request시 `content`라는 키 값을 넣어야하는데, 실수로 `이상한content key값`을 넣어주고 있어요.
이런 경우, `content`라는 키 값이 없기때문에 `이상한content key값`에 적혀있는 `"새로 생성하는 내용"`이라는 정보가 유실되는 것이죠!

문제의 원인은 확실히 알았는데..
해결할 방법이 떠오르질 않아서 라자냐에게 조언을 구했던 거에요😭
해결할 수 없는 문제면, 이 문제를 어떤 식으로 클라이언트에게 따로 알려줘야 할까요?
그냥 API문서에 남기는 방향으로 해야할까요..??

2021-08-03 13:10 UTC, wonhee009 commented
@KangKyung @inwoodev 

- GET방식에 관한 고민

```swift
switch request.parameters.get("")
```

get("")이면 파라미터에서 아무것도 안 가져오고 있는거 아닌가요?
get("category")로 하면 작동할까요?
음... 이 부분은 우선 기능에는 문제가 없으니 이후 스텝에서 계속 고민해봐도 좋을꺼 같아요!

> 더불어, 코드가 중복 되더라도 하나의 책임을 갖는 메서드를 여러개 만드는 것이
하나의 메서드 안에서 분기처리를 하는 것 보다 더 객체지향적(단일책임원칙)이라고 생각이 문득 들었는데요..!
라자냐는 이 부분에 대해서는 어떻게 생각하실지 궁금해요🤔

음 우선 하나의 책임을 갖는 메서드를 여러개 만드는 부분은 현재는 todo, doing, done 3가지의 타입만 있지만 만약 더 늘어난다면 메서드도 늘어나겠죠.
그리고 현재 코드를 보면 3가지 타입의 로직이 완전히 동일하고 "todo", "doing", "done"과 같은 파라미터만 달라지는거로 보이네요.
만약 저의 경우라면 재사용성 측면과 확장성을 고려해서 메서드 안에서 분기를 처리할거 같아요.


- optional type에 대한 고민

네 이해했습니다.
흠... 그런데 이 부분이 왜 문제라고 생각하는건가요?
이미 클라이언트측과 "content"라는 키값을 model의 키값으로 사용하는 것으로 명세를 합의했는데 잘못된 키값을 넘겨주는건 클라이언트측의 문제 아닐까요?

2021-08-05 07:08 UTC, KangKyung commented
@wonhee009 
> get("")이면 파라미터에서 아무것도 안 가져오고 있는거 아닌가요?
get("category")로 하면 작동할까요?

`"category"`를 넣었는데 안됐어요😢
step4에서 다시 고민해보도록 하겠습니다..!

> 이미 클라이언트측과 "content"라는 키값을 model의 키값으로 사용하는 것으로 명세를 합의했는데 잘못된 키값을 넘겨주는건 클라이언트측의 문제 아닐까요?

저희의 걱정이 지나쳤군요😅
말씀을 이해했습니다! ㅎㅎㅎ

넘어가서 더 생각해 보겠습니다. merge부탁 드릴게요🙏🏼

2021-08-05 07:13 UTC, wonhee009 commented
@KangKyung @inwoodev 

네엡! 저도 다시 한 번 봐볼게요! 동작에는 문제가 없으니 다음 스텝에서 좀 더 고민해보도록 해요!
"잘못된 키값"에 대한 부분을 방지하기 위해서 클라이언트와 서버끼리 합의를 거쳐서 명세서를 공유한다고 생각해요ㅎㅎ

스텝3 수고하셨습니다! 스텝4에서 보아요!🎉

2021-08-05 07:13 UTC, merged